openapi: 3.0.3
info:
  title: Supervisor API
  termsOfService: ""
  license:
    name: ' '
    url: ''
  version: 1.0.0
servers:
- url: http://test.supervisor.com/
tags:
- name: setup
  description: Methods that have to do with creating a test
- name: manage
  description: Methods to do with managing existing tests
- name: controls
  description: Methods used during a test for controlling the bots
paths:
  /free/verify:
    get:
      tags:
      - setup
      description: Adds a website to your panel
      operationId: freeVerifyGET
      parameters:
      - name: url
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: example.com
      responses:
        "200":
          description: Success
          content:
            text/plain; charset=utf-8:
              example:
                value: (html)
      x-swagger-router-controller: Setup
  /start:
    get:
      tags:
      - setup
      description: Starts a test on a website
      operationId: startGET
      parameters:
      - name: url
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: example.com
      responses:
        "200":
          description: Success
          content:
            text/plain; charset=utf-8:
              example:
                value: (html)
      x-swagger-router-controller: Setup
  /organizations/{bot_session_id}/coupons:
    post:
      tags:
      - manage
      summary: Used to apply a coupon code
      description: Applies a coupon
      operationId: organizationsBot_session_idCouponsPOST
      parameters:
      - name: bot_session_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bot_session_id_coupons_body'
        required: true
      responses:
        default:
          description: TODO
      x-swagger-router-controller: Manage
  /v1/bot_sessions/{bot_session_id}/scale:
    put:
      tags:
      - controls
      description: Scales bot amount
      operationId: v1Bot_sessionsBot_session_idScalePUT
      parameters:
      - name: bot_session_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bot_session_id_scale_body'
        required: true
      responses:
        default:
          description: TODO
      x-swagger-router-controller: Controls
  /v1/bot_sessions/{bot_session_id}/reset_browsers:
    put:
      tags:
      - controls
      description: resets all bots
      operationId: v1Bot_sessionsBot_session_idReset_browsersPUT
      parameters:
      - name: bot_session_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bot_session_id_reset_browsers_body'
        required: true
      responses:
        default:
          description: TODO
      x-swagger-router-controller: Controls
  /v1/bot_sessions/{bot_session_id}/reset_metrics:
    put:
      tags:
      - controls
      description: resets metrics data
      operationId: v1Bot_sessionsBot_session_idReset_metricsPUT
      parameters:
      - name: bot_session_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bot_session_id_reset_metrics_body'
        required: true
      responses:
        default:
          description: TODO
      x-swagger-router-controller: Controls
  /v1/bot_sessions/{bot_session_id}/play:
    put:
      tags:
      - controls
      description: Sends bot(s) over to target site
      operationId: v1Bot_sessionsBot_session_idPlayPUT
      parameters:
      - name: bot_session_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bot_session_id_play_body'
        required: true
      responses:
        default:
          description: TODO
      x-swagger-router-controller: Controls
  /v1/bot_sessions/{bot_session_id}/stop:
    put:
      tags:
      - controls
      description: Stops all bots
      operationId: v1Bot_sessionsBot_session_idStopPUT
      parameters:
      - name: bot_session_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bot_session_id_stop_body'
        required: true
      responses:
        default:
          description: TODO
      x-swagger-router-controller: Controls
components:
  schemas:
    bot_session_id_coupons_body:
      type: object
      properties:
        authenticity_token:
          type: string
        coupon[code]:
          type: string
        commit:
          type: string
          example: Apply
    bot_session_id_scale_body:
      type: object
      properties:
        replicas:
          type: integer
        job_id:
          type: string
    bot_session_id_reset_browsers_body:
      type: object
      properties:
        job_id:
          type: string
    bot_session_id_reset_metrics_body:
      type: object
      properties:
        job_id:
          type: string
    v1bot_sessionsbot_session_idplay_explore_settings:
      type: object
      properties:
        max_page_load_seconds:
          type: string
          example: "20"
        max_initial_load_seconds:
          type: string
          example: "30"
        pages:
          type: string
          example: "15"
        view_page_seconds:
          type: string
          example: "5"
        whitelist_matcher:
          type: string
        blacklist_matcher:
          type: string
        initial_load_max:
          type: string
          example: "6"
    bot_session_id_play_body:
      type: object
      properties:
        job_id:
          type: string
        rampup_period:
          type: string
          example: "1"
        rampup_users:
          type: string
          example: "1"
        bots_limit:
          type: string
          example: "1"
        useragent:
          type: string
          example: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101
            Firefox/47.0
        errored_bots_threshold:
          type: string
          example: "5"
        min_bots_threshold:
          type: string
          example: "1"
        restart_errored_every:
          type: string
          example: "1"
        latency:
          type: string
          example: "25"
        download:
          type: string
          example: "25"
        upload:
          type: string
          example: "10"
        block_google_analytics:
          type: boolean
          example: true
        webcam_video_on:
          type: boolean
          example: true
        webcam_audio_on:
          type: boolean
          example: true
        explore_settings:
          $ref: '#/components/schemas/v1bot_sessionsbot_session_idplay_explore_settings'
    bot_session_id_stop_body:
      type: object
      properties:
        job_id:
          type: string
        bot_id:
          type: string
